#!/bin/bash


clear

cat  <<  EOF
██╗  ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗
██║  ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝
███████║   ██║   ██║   ██║██║   ██║██║     ███████╗
██╔══██║   ██║   ██║   ██║██║   ██║██║     ╚════██║
██║  ██║   ██║   ╚██████╔╝╚██████╔╝███████╗███████║
╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝

EOF

mkdir HackToolkit1.1
cd HackToolkit1.1

# Git Repos...

git clone https://github.com/DanMcInerney/shellshock-hunter
git clone https://github.com/DanMcInerney/shellshock-hunter-google
git clone https://github.com/DanMcInerney/wifijammer
git clone https://github.com/darkoperator/dnsrecon
git clone https://github.com/ddos-defense/bohatei
git clone https://github.com/desaster/kippo
git clone https://github.com/devttys0/binwalk
git clone https://github.com/digininja/CeWL
git clone https://github.com/Dionach/CMSmap
git clone https://github.com/dloss/python-pentest-tools
git clone https://github.com/DoddyHackman/Arsenal_X
git clone https://github.com/DominikSchlecht/pyDirBuster
git clone https://github.com/dotfighter/torshammer
git clone https://github.com/dripcap/dripcap
git clone https://github.com/EgeBalci/The-Eye
git clone https://github.com/EnableSecurity/wafw00f
git clone https://github.com/endgameinc/binarypig
git clone https://github.com/epinna/weevely3
git clone https://github.com/Ettercap/ettercap
git clone https://github.com/evilsocket/bettercap
git clone https://github.com/ex0dus-0x/brut3k1t
git clone https://github.com/ex0dus-0x/dedsploit
git clone https://github.com/fgeek/pyfiscan
git clone https://github.com/foospidy/HoneyPy
git clone https://github.com/frdmn/findmyhash
git clone https://github.com/g0tmi1k/mpc
git clone https://github.com/gabrielrcouto/reaver-wps
git clone https://github.com/mempodippy/vlany.git
git clone https://github.com/unix-thrust/beurk.git
git clone https://github.com/nmap/nmap.git
git clone https://github.com/leviathan-framework/leviathan.git
git clone https://github.com/n1nj4sec/pupy/tree/master/client
git clone https://github.com/valyala/goloris.git
git clone https://github.com/radare/radare2.git
git clone https://github.com/OffensivePython/Saddam.git
git clone https://github.com/botherder/virustotal.git
git clone https://github.com/Microsoft/binskim.git
git clone https://github.com/0xd4d/dnSpy.git
git clone https://github.com/lowleveldesign/wtrace.git
git clone https://github.com/spesmilo/electrum.git
git clone https://github.com/bitcoin-wallet/bitcoin-wallet.git
git clone https://github.com/tuxotron/xvwa_lamp_container.git
git clone https://github.com/JonathanSalwan/Triton.git
git clone https://github.com/hypsurus/weeman.git
git clone https://github.com/krmaxwell/tinfoleak
git clone https://github.com/secretsquirrel/fido.git
git clone https://github.com/gentilkiwi/mimikatz.git
git clone https://github.com/SecurityInnovation/AuthMatrix.git
git clone https://github.com/akheron/jansson
git clone https://github.com/wolf9466/cpuminer-multi.git
git clone https://github.com/tsiv/ccminer-cryptonight.git
git clone https://github.com/evilsocket/bettercap-proxy-modules.git
git clone https://github.com/Raikia/FiercePhish.git
git clone https://github.com/adaptivethreat/Empire.git
git clone https://github.com/gophish/gophish.git
git clone https://github.com/DhavalKapil/icmptunnel.git
git clone https://github.com/sqlmapproject/sqlmap.git
git clone https://github.com/davidpepper/fierce-domain-scanner.git
git clone https://github.com/Mebus/cupp.git
git clone https://github.com/digininja/CeWL.git
git clone https://github.com/iagox86/dnscat2.git
git clone https://github.com/ryhanson/phishery.git
git clone https://github.com/JusticeRage/Manalyze.git
git clone git://git.kali.org/packages/exploitdb.git
git clone https://github.com/trustedsec/social-engineer-toolkit.git
git clone https://github.com/roobixx/cowpatty.git
git clone https://github.com/hashcat/hashcat.git
git clone https://github.com/laramies/theHarvester.git
git clone https://github.com/secretsquirrel/the-backdoor-factory.git
git clone https://github.com/EnableSecurity/wafw00f.git
git clone https://github.com/stephenfewer/ReflectiveDLLInjection.git
git clone https://github.com/kstaken/dockerfile-examples.git
git clone https://github.com/xmendez/wfuzz.git
git clone https://github.com/pxb1988/dex2jar.git
git clone git://git.kali.org/packages/dirbuster.git
git clone https://github.com/deltaxflux/fluxion.git
git clone git://git.kali.org/packages/joomscan.git
git clone https://github.com/hexploitable/MEMSCAN.git
git clone https://github.com/hiddenillusion/AnalyzePDF.git
git clone https://github.com/smalot/pdfparser.git
git clone https://github.com/jesparza/peepdf.git
git clone https://github.com/reverse-shell/routersploit.git
git clone https://github.com/google/sandbox-attacksurface-analysis-tools.git
git clone https://github.com/sophron/wifiphisher.git
git clone https://github.com/wpscanteam/wpscan.git
git clone https://github.com/Yara-Rules/rules.git
git clone git://github.com/cuckoosandbox/cuckoo.git
git clone https://github.com/juansacco/exploitpack.git
git clone https://github.com/BlackArch/webshells.git
git clone https://github.com/EgeBalci/HERCULES.git
git clone https://github.com/EgeBalci/Cminer.git
git clone https://github.com/EgeBalci/The-Eye.git
git clone https://github.com/DanMcInerney/wifijammer.git
git clone https://git.kali.org/packages/ace-voip.git
git clone https://git.kali.org/packages/amap.git
git clone https://git.kali.org/packages/cisco-auditing-tool.git
git clone https://git.kali.org/packages/cisco-global-exploiter.git
git clone https://git.kali.org/packages/cisco-ocs.git
git clone https://git.kali.org/packages/cisco-torch.git
git clone https://bitbucket.org/LaNMaSteR53/recon-ng
git clone https://github.com/0xd4d/dnSpy
git clone https://github.com/1aN0rmus/TekDefense-Automater
git clone https://github.com/1N3/Findsploit
git clone https://github.com/1N3/Sn1per
git clone https://github.com/4shadoww/hakkuframework
git clone https://github.com/adaptivethreat/Empire
git clone https://github.com/AeonDave/doork
git clone https://github.com/aircrack-ng/aircrack-ng
git clone https://github.com/ajinabraham/Mobile-Security-Framework-MobSF
git clone https://github.com/AlisamTechnology/ATSCAN
git clone https://github.com/allfro/sploitego
git clone https://github.com/andresriancho/w3af
git clone https://github.com/aol/moloch
git clone https://github.com/appknox/AFE
git clone https://github.com/Arachni/arachni
git clone https://github.com/Aralhach/bashobfus
git clone https://github.com/b3mb4m/shellsploit-framework
git clone https://github.com/bartobri/no-more-secrets
git clone https://github.com/beefproject/beef
git clone https://github.com/BlackArch/rainbowcrack
git clone https://github.com/blindfuzzy/LHF
git clone https://github.com/bounteous/libenom
git clone https://github.com/BRDumps/extract-hashes
git clone https://github.com/BreakingMalwareResearch/atom-bombing
git clone https://github.com/byt3bl33d3r/chrome-decrypter
git clone https://github.com/byt3bl33d3r/pth-toolkit
git clone https://github.com/certsocietegenerale/FIR
git clone https://github.com/certtools/intelmq
git clone https://github.com/Cewlt/SkypeMass
git clone https://github.com/chaitin/sqlchop
git clone https://github.com/chinoogawa/fbht
git clone https://github.com/cloughrm/Pastebin-Scraper
git clone https://github.com/commixproject/commix
git clone https://github.com/cxdy/pybomber
git clone https://github.com/D35m0nd142/Kadabra
git clone https://github.com/danielmiessler/SecLists
git clone https://github.com/DanMcInerney/shellshock-hunter
git clone https://github.com/DanMcInerney/shellshock-hunter-google
git clone https://github.com/DanMcInerney/wifijammer
git clone https://github.com/darkoperator/dnsrecon
git clone https://github.com/ddos-defense/bohatei
git clone https://github.com/desaster/kippo
git clone https://github.com/devttys0/binwalk
git clone https://github.com/digininja/CeWL
git clone https://github.com/Dionach/CMSmap
git clone https://github.com/dloss/python-pentest-tools
git clone https://github.com/DoddyHackman/Arsenal_X
git clone https://github.com/DominikSchlecht/pyDirBuster
git clone https://github.com/dotfighter/torshammer
git clone https://github.com/dripcap/dripcap
git clone https://github.com/EgeBalci/The-Eye
git clone https://github.com/EnableSecurity/wafw00f
git clone https://github.com/endgameinc/binarypig
git clone https://github.com/epinna/weevely3
git clone https://github.com/Ettercap/ettercap
git clone https://github.com/evilsocket/bettercap
git clone https://github.com/ex0dus-0x/brut3k1t
git clone https://github.com/ex0dus-0x/dedsploit
git clone https://github.com/fgeek/pyfiscan
git clone https://github.com/foospidy/HoneyPy
git clone https://github.com/frdmn/findmyhash
git clone https://github.com/g0tmi1k/mpc
git clone https://github.com/gabrielrcouto/reaver-wps
git clone https://github.com/Gallopsled/pwntools
git clone https://github.com/gamelinux/passivedns
git clone https://github.com/GDSSecurity/Windows-Exploit-Suggester
git clone https://github.com/georgiaw/Smartphone-Pentest-Framework
git clone https://github.com/google/grr
git clone https://github.com/google/rowhammer-test
git clone https://github.com/google/stenographer
git clone https://github.com/googleinurl/SCANNER-INURLBR
git clone https://github.com/GouveaHeitor/nipe
git clone https://github.com/graniet/chromebackdoor
git clone https://github.com/HackerOrientado/BypassCF
git clone https://github.com/hahwul/droid-hunter
git clone https://github.com/hashcat/hashcat
git clone https://github.com/hatRiot/clusterd
git clone https://github.com/hatRiot/zarp
git clone https://github.com/hellman/xortool
git clone https://github.com/HiroshiManRise/anonym8
git clone https://github.com/Hood3dRob1n/BinGoo
git clone https://github.com/huntergregal/scansploit
git clone https://github.com/hvqzao/liffy
git clone https://github.com/Hypsurus/weeman
git clone https://github.com/infobyte/evilgrade
git clone https://github.com/j91321/rext
git clone https://github.com/jaromil/HasciiCam
git clone https://github.com/jh00nbr/Routerhunter-2.0
git clone https://github.com/JoeDog/siege
git clone https://github.com/JohnTroony/php-webshells
git clone https://github.com/JPaulMora/Pyrit
git clone https://github.com/jsvine/waybackpack
git clone https://github.com/juansacco/exploitpack
git clone https://github.com/Jumpst3r/AsciiToDucky
git clone https://github.com/k4m4/onioff
git clone https://github.com/kevthehermit/dc-toolkit
git clone https://github.com/kevthehermit/RATDecoders
git clone https://github.com/knownsec/Pocsuite
git clone https://github.com/korczis/foremost
git clone https://github.com/kurobeats/fimap
git clone https://github.com/lanjelot/patator
git clone https://github.com/leebaird/discover
git clone https://github.com/lhr0909/PythonObfuscator
git clone https://github.com/liftoff/pyminifier
git clone https://github.com/lightbulb-framework/lightbulb-framework
git clone https://github.com/luisgg/ophcrack
git clone https://github.com/m0nad/HellRaiser
git clone https://github.com/m3pt0r/l0l
git clone https://github.com/magnumripper/JohnTheRipper
git clone https://github.com/marshyski/sshwatch
git clone https://github.com/merculite/BLE-Security
git clone https://github.com/micahflee/onionshare
git clone https://github.com/mikeryan/crackle
git clone https://github.com/misterch0c/malSploitBase
git clone https://github.com/mitmproxy/mitmproxy
git clone https://github.com/mthbernardes/EvilTool
git clone https://github.com/nbs-system/naxsi
git clone https://github.com/nmap/nmap
git clone https://github.com/NORMA-Inc/AtEar
git clone https://github.com/OsandaMalith/LFiFreak
git clone https://github.com/P0cL4bs/Kadimus
git clone https://github.com/ParrotSec/car-hacking-tools
git clone https://github.com/PenturaLabs/Linux_Exploit_Suggester
git clone https://github.com/praetorian-inc/Hob0Rules
git clone https://github.com/psypanda/hashID
git clone https://github.com/r00t-3xp10it/morpheus
git clone https://github.com/radare/radare2
git clone https://github.com/rafael-santiago/pig
git clone https://github.com/ReclaimYourPrivacy/eschalot
git clone https://github.com/reverse-shell/routersploit
git clone https://github.com/reyammer/shellnoob
git clone https://github.com/rezasp/joomscan
git clone https://github.com/rezasp/vbscan
git clone https://github.com/rfunix/Pompem
git clone https://github.com/rsmudge/armitage
git clone https://github.com/s3inlc/holm
git clone https://github.com/SafeStack/ava
git clone https://github.com/SageHack/cloud-buster
git clone https://github.com/SageHack/cloudflare-resolver
git clone https://github.com/samratashok/Kautilya
git clone https://github.com/samratashok/nishang
git clone https://github.com/savio-code/ghost-phisher
git clone https://github.com/Screetsec/Brutal
git clone https://github.com/Screetsec/Dracnmap
git clone https://github.com/Screetsec/TheFatRat
git clone https://github.com/SECFORCE/sparta
git clone https://github.com/secretsquirrel/the-backdoor-factory
git clone https://github.com/securestate/termineter
git clone https://github.com/seifreed/dirb
git clone https://github.com/sensepost/DET
git clone https://github.com/sensepost/kwetza
git clone https://github.com/sensepost/xrdp
git clone https://github.com/shawarkhanethicalhacker/D-TECT
git clone https://github.com/simsong/tcpflow
git clone https://github.com/sleuthkit/autopsy
git clone https://github.com/sleuthkit/sleuthkit
git clone https://github.com/sophron/wifiphisher
git clone https://github.com/SpiderLabs/jboss-autopwn
git clone https://github.com/suraj-root/spade
git clone https://github.com/tcstool/fireaway
git clone https://github.com/tcstool/NoSQLMap
git clone https://github.com/TheRook/subbrute
git clone https://github.com/thesp0nge/dawnscanner
git clone https://github.com/timwr/CVE-2016-5195
git clone https://github.com/tnich/honssh
git clone https://github.com/tomac/yersinia
git clone https://github.com/trustedsec/ptf
git clone https://github.com/TryCatchHCF/Cloakify
git clone https://github.com/ufrisk/pcileech
git clone https://github.com/urbanadventurer/WhatWeb
git clone https://github.com/USArmyResearchLab/Dshell
git clone https://github.com/v3n0m-Scanner/V3n0M-Scanner
git clone https://github.com/vk496/linset
git clone https://github.com/volatilityfoundation/volatility
git clone https://github.com/vusec/drammer
git clone https://github.com/vvalien/SharpMeter
git clone https://github.com/WhiteMatt3r/Skype-Tool
git clone https://github.com/wi-fi-analyzer/mdk3-master
git clone https://github.com/wick2o/gitdigger
git clone https://github.com/wiire/pixiewps
git clone https://github.com/wireghoul/dotdotpwn
git clone https://github.com/wpscanteam/wpscan
git clone https://github.com/x3omdax/PenBox
git clone https://github.com/yaph/domxssscanner
git clone https://github.com/ysrc/F-Scrack
git clone https://github.com/zennro/fbht-linux
git clone https://github.com/zeroq/amun
git clone https://github.com/zscproject/OWASP-ZSC
git clone https://www.kismetwireless.net/git/kismet.git


echo FINISH!!! Now ENJOY!!!
clear
ls
